# Generated by Django 3.1.7 on 2021-05-25 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.BigIntegerField(blank=True, default=0)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'device',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.BigIntegerField(blank=True)),
                ('price_now', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adult', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'room',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.BigIntegerField(blank=True)),
                ('voucher', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rents.rentdetail')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='room.room')),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='rooms', to='room.Service')),
            ],
            options={
                'db_table': 'room_service',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_device', to='room.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_device', to='room.room')),
            ],
            options={
                'db_table': 'room_device',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='room_categorys', to='room.Service')),
            ],
            options={
                'db_table': 'room_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.roomcategory'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel'),
        ),
    ]
