# Generated by Django 3.1.7 on 2021-05-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='rent',
        ),
    ]
