# Generated by Django 3.1.7 on 2021-05-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_roomservice_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='room.Service'),
        ),
        migrations.DeleteModel(
            name='RoomService',
        ),
    ]
