# Generated by Django 3.1.7 on 2021-05-20 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210520_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('devices', models.ManyToManyField(blank=True, null=True, related_name='room_device', to='room.Device')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_device', to='room.room')),
            ],
            options={
                'db_table': 'room_device',
            },
        ),
    ]
