# Generated by Django 3.1.7 on 2021-05-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roomdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdevice',
            name='devices',
        ),
        migrations.AddField(
            model_name='roomdevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_device', to='room.device'),
        ),
    ]
