# Generated by Django 3.1.7 on 2021-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210528_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(default='none', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
