# Generated by Django 3.1.7 on 2021-05-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20210520_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomservice',
            options={'ordering': ['id']},
        ),
    ]
