# Generated by Django 3.1.7 on 2021-05-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20210525_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='room.Service'),
        ),
    ]
