# Generated by Django 3.1.7 on 2021-05-25 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20210525_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='room.room'),
        ),
    ]
