# Generated by Django 3.1.7 on 2021-05-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0006_auto_20210524_1307'),
        ('room', '0007_auto_20210525_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='rents.rentdetail'),
        ),
    ]
