# Generated by Django 3.1.7 on 2021-05-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_roomservice_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='room.room'),
        ),
    ]
