# Generated by Django 3.1.7 on 2021-05-20 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210520_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(default=[uuid.UUID('e2093191-f98e-4402-bcaf-1ddfda449673')], related_name='users', to='users.Role'),
        ),
    ]
