# Generated by Django 3.1.7 on 2021-05-20 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210520_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, default=[uuid.UUID('e2093191-f98e-4402-bcaf-1ddfda449673')], null=True, related_name='users', to='users.Role'),
        ),
    ]
