# Generated by Django 3.1.7 on 2021-05-28 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rents', '0003_rent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RENT', 'RENT'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='rents.rent')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['created_at'],
            },
        ),
    ]
