# Generated by Django 3.1.7 on 2021-05-31 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210528_0915'),
        ('notification', '0002_auto_20210531_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hotel',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
