# Generated by Django 3.1.7 on 2021-05-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalAmount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='hotel.hotel')),
                ('rent', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='rents.rent')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_bill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['created_at'],
            },
        ),
    ]
