# Generated by Django 3.1.7 on 2021-05-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comfortable', models.IntegerField()),
                ('address', models.IntegerField()),
                ('wifi_free', models.IntegerField()),
                ('staff', models.IntegerField()),
                ('convenirent', models.IntegerField()),
                ('clean', models.IntegerField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('discount', models.BigIntegerField(blank=True, null=True)),
                ('totalAmount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rent',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentDetail',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('voucher', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rents.feedback')),
                ('rent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='rents.rent')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='room.room')),
            ],
            options={
                'db_table': 'rent_detail',
                'ordering': ['created_at'],
            },
        ),
    ]
