# Generated by Django 3.1.7 on 2021-05-21 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='users',
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL),
        ),
    ]
