# Generated by Django 3.1.7 on 2021-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20210525_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
