# Generated by Django 3.1.7 on 2021-06-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210528_0915'),
        ('rents', '0003_rent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='hotel',
            field=models.ForeignKey(default='d90ed539-8205-4472-8155-f4c9640096bd', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
