# Generated by Django 3.1.7 on 2021-05-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_auto_20210521_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetail',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent', to='rents.feedback'),
        ),
    ]
