# Generated by Django 3.1.7 on 2021-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_rent_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
