# Generated by Django 3.1.7 on 2021-06-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0005_rent_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='totalAmount',
            new_name='total_amount',
        ),
    ]
