# Generated by Django 3.1.7 on 2021-05-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210521_1059'),
        ('rents', '0006_auto_20210524_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks', to='hotel.hotel'),
        ),
    ]
