# Generated by Django 3.1.7 on 2021-05-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='hotel.hotel'),
        ),
    ]
